### ISSUE TITLE
Create new HTML page - AI

### ISSUE THREAD

**Issue by yunjins** [KaylaCrush/group3project#11]
Adding a page for AI

**Comment by mirembekaggwa** [comment]
going to take a stab at this...

**Comment by yunjins** [comment]
I think this is a duplicate task that I forgot to close, I already created the AI page, but it's just missing the information to be added. I just saw Maili did some research on AI

**Comment by mirembekaggwa** [comment]
You are right. I went ahead and moved it to completed.
